<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      
        DB::table('countries')->delete();

        $countries = array(
            array('iso' => 'AF','name' => 'AFGHANISTAN', 'country_code' => '+93'),
            array('iso' => 'AL','name' => 'ALBANIA', 'country_code' => '+355'),
            array('iso' => 'DZ','name' => 'ALGERIA', 'country_code' => '+213'),
            array('iso' => 'AS','name' => 'AMERICAN SAMOA', 'country_code' => '+1684'),
            array('iso' => 'AD','name' => 'ANDORRA', 'country_code' => '+376'),
            array('iso' => 'AO','name' => 'ANGOLA', 'country_code' => '+244'),
            array('iso' => 'AI','name' => 'ANGUILLA', 'country_code' => '+1264'),
            array('iso' => 'AQ','name' => 'ANTARCTICA', 'country_code' => '+0'),
            array('iso' => 'AG','name' => 'ANTIGUA AND BARBUDA', 'country_code' => '+1268'),
            array('iso' => 'AR','name' => 'ARGENTINA', 'country_code' => '+54'),
            array('iso' => 'AM','name' => 'ARMENIA', 'country_code' => '+374'),
            array('iso' => 'AW','name' => 'ARUBA', 'country_code' => '+297'),
            array('iso' => 'AU','name' => 'AUSTRALIA', 'country_code' => '+61'),
            array('iso' => 'AT','name' => 'AUSTRIA', 'country_code' => '+43'),
            array('iso' => 'AZ','name' => 'AZERBAIJAN', 'country_code' => '+994'),
            array('iso' => 'BS','name' => 'BAHAMAS', 'country_code' => '+1242'),
            array('iso' => 'BH','name' => 'BAHRAIN', 'country_code' => '+973'),
            array('iso' => 'BD','name' => 'BANGLADESH', 'country_code' => '+880'),
            array('iso' => 'BB','name' => 'BARBADOS', 'country_code' => '+1246'),
            array('iso' => 'BY','name' => 'BELARUS', 'country_code' => '+375'),
            array('iso' => 'BE','name' => 'BELGIUM', 'country_code' => '+32'),
            array('iso' => 'BZ','name' => 'BELIZE', 'country_code' => '+501'),
            array('iso' => 'BJ','name' => 'BENIN', 'country_code' => '+229'),
            array('iso' => 'BM','name' => 'BERMUDA', 'country_code' => '+1441'),
            array('iso' => 'BT','name' => 'BHUTAN', 'country_code' => '+975'),
            array('iso' => 'BO','name' => 'BOLIVIA', 'country_code' => '+591'),
            array('iso' => 'BA','name' => 'BOSNIA AND HERZEGOVINA', 'country_code' => '+387'),
            array('iso' => 'BW','name' => 'BOTSWANA', 'country_code' => '+267'),
            array('iso' => 'BV','name' => 'BOUVET ISLAND', 'country_code' => '+0'),
            array('iso' => 'BR','name' => 'BRAZIL', 'country_code' => '+55'),
            array('iso' => 'IO','name' => 'BRITISH INDIAN OCEAN TERRITORY', 'country_code' => '+246'),
            array('iso' => 'BN','name' => 'BRUNEI DARUSSALAM', 'country_code' => '+673'),
            array('iso' => 'BG','name' => 'BULGARIA', 'country_code' => '+359'),
            array('iso' => 'BF','name' => 'BURKINA FASO', 'country_code' => '+226'),
            array('iso' => 'BI','name' => 'BURUNDI', 'country_code' => '+257'),
            array('iso' => 'KH','name' => 'CAMBODIA', 'country_code' => '+855'),
            array('iso' => 'CM','name' => 'CAMEROON', 'country_code' => '+237'),
            array('iso' => 'CA','name' => 'CANADA', 'country_code' => '+1'),
            array('iso' => 'CV','name' => 'CAPE VERDE', 'country_code' => '+238'),
            array('iso' => 'KY','name' => 'CAYMAN ISLANDS', 'country_code' => '+1345'),
            array('iso' => 'CF','name' => 'CENTRAL AFRICAN REPUBLIC', 'country_code' => '+236'),
            array('iso' => 'TD','name' => 'CHAD', 'country_code' => '+235'),
            array('iso' => 'CL','name' => 'CHILE', 'country_code' => '+56'),
            array('iso' => 'CN','name' => 'CHINA', 'country_code' => '+86'),
            array('iso' => 'CX','name' => 'CHRISTMAS ISLAND', 'country_code' => '+61'),
            array('iso' => 'CC','name' => 'COCOS (KEELING) ISLANDS', 'country_code' => '+672'),
            array('iso' => 'CO','name' => 'COLOMBIA', 'country_code' => '+57'),
            array('iso' => 'KM','name' => 'COMOROS', 'country_code' => '+269'),
            array('iso' => 'CG','name' => 'CONGO', 'country_code' => '+242'),
            array('iso' => 'CD','name' => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'country_code' => '+242'),
            array('iso' => 'CK','name' => 'COOK ISLANDS', 'country_code' => '+682'),
            array('iso' => 'CR','name' => 'COSTA RICA', 'country_code' => '+506'),
            array('iso' => 'CI','name' => 'COTE D\'IVOIRE', 'country_code' => '+225'),
            array('iso' => 'HR','name' => 'CROATIA', 'country_code' => '+385'),
            array('iso' => 'CU','name' => 'CUBA', 'country_code' => '+53'),
            array('iso' => 'CY','name' => 'CYPRUS', 'country_code' => '+357'),
            array('iso' => 'CZ','name' => 'CZECH REPUBLIC', 'country_code' => '+420'),
            array('iso' => 'DK','name' => 'DENMARK', 'country_code' => '+45'),
            array('iso' => 'DJ','name' => 'DJIBOUTI', 'country_code' => '+253'),
            array('iso' => 'DM','name' => 'DOMINICA', 'country_code' => '+1767'),
            array('iso' => 'DO','name' => 'DOMINICAN REPUBLIC', 'country_code' => '+1809'),
            array('iso' => 'EC','name' => 'ECUADOR', 'country_code' => '+593'),
            array('iso' => 'EG','name' => 'EGYPT', 'country_code' => '+20'),
            array('iso' => 'SV','name' => 'EL SALVADOR', 'country_code' => '+503'),
            array('iso' => 'GQ','name' => 'EQUATORIAL GUINEA', 'country_code' => '+240'),
            array('iso' => 'ER','name' => 'ERITREA', 'country_code' => '+291'),
            array('iso' => 'EE','name' => 'ESTONIA', 'country_code' => '+372'),
            array('iso' => 'ET','name' => 'ETHIOPIA', 'country_code' => '+251'),
            array('iso' => 'FK','name' => 'FALKLAND ISLANDS (MALVINAS)', 'country_code' => '+500'),
            array('iso' => 'FO','name' => 'FAROE ISLANDS', 'country_code' => '+298'),
            array('iso' => 'FJ','name' => 'FIJI', 'country_code' => '+679'),
            array('iso' => 'FI','name' => 'FINLAND', 'country_code' => '+358'),
            array('iso' => 'FR','name' => 'FRANCE', 'country_code' => '+33'),
            array('iso' => 'GF','name' => 'FRENCH GUIANA', 'country_code' => '+594'),
            array('iso' => 'PF','name' => 'FRENCH POLYNESIA', 'country_code' => '+689'),
            array('iso' => 'TF','name' => 'FRENCH SOUTHERN TERRITORIES', 'country_code' => '+0'),
            array('iso' => 'GA','name' => 'GABON', 'country_code' => '+241'),
            array('iso' => 'GM','name' => 'GAMBIA', 'country_code' => '+220'),
            array('iso' => 'GE','name' => 'GEORGIA', 'country_code' => '+995'),
            array('iso' => 'DE','name' => 'GERMANY', 'country_code' => '+49'),
            array('iso' => 'GH','name' => 'GHANA', 'country_code' => '+233'),
            array('iso' => 'GI','name' => 'GIBRALTAR', 'country_code' => '+350'),
            array('iso' => 'GR','name' => 'GREECE', 'country_code' => '+30'),
            array('iso' => 'GL','name' => 'GREENLAND', 'country_code' => '+299'),
            array('iso' => 'GD','name' => 'GRENADA', 'country_code' => '+1473'),
            array('iso' => 'GP','name' => 'GUADELOUPE', 'country_code' => '+590'),
            array('iso' => 'GU','name' => 'GUAM', 'country_code' => '+1671'),
            array('iso' => 'GT','name' => 'GUATEMALA', 'country_code' => '+502'),
            array('iso' => 'GN','name' => 'GUINEA', 'country_code' => '+224'),
            array('iso' => 'GW','name' => 'GUINEA-BISSAU', 'country_code' => '+245'),
            array('iso' => 'GY','name' => 'GUYANA', 'country_code' => '+592'),
            array('iso' => 'HT','name' => 'HAITI', 'country_code' => '+509'),
            array('iso' => 'HM','name' => 'HEARD ISLAND AND MCDONALD ISLANDS', 'country_code' => '+0'),
            array('iso' => 'VA','name' => 'HOLY SEE (VATICAN CITY STATE)', 'country_code' => '+39'),
            array('iso' => 'HN','name' => 'HONDURAS', 'country_code' => '+504'),
            array('iso' => 'HK','name' => 'HONG KONG', 'country_code' => '+852'),
            array('iso' => 'HU','name' => 'HUNGARY', 'country_code' => '+36'),
            array('iso' => 'IS','name' => 'ICELAND', 'country_code' => '+354'),
            array('iso' => 'IN','name' => 'INDIA', 'country_code' => '+91'),
            array('iso' => 'ID','name' => 'INDONESIA', 'country_code' => '+62'),
            array('iso' => 'IR','name' => 'IRAN, ISLAMIC REPUBLIC OF', 'country_code' => '+98'),
            array('iso' => 'IQ','name' => 'IRAQ', 'country_code' => '+964'),
            array('iso' => 'IE','name' => 'IRELAND', 'country_code' => '+353'),
            array('iso' => 'IL','name' => 'ISRAEL', 'country_code' => '+972'),
            array('iso' => 'IT','name' => 'ITALY', 'country_code' => '+39'),
            array('iso' => 'JM','name' => 'JAMAICA', 'country_code' => '+1876'),
            array('iso' => 'JP','name' => 'JAPAN', 'country_code' => '+81'),
            array('iso' => 'JO','name' => 'JORDAN', 'country_code' => '+962'),
            array('iso' => 'KZ','name' => 'KAZAKHSTAN', 'country_code' => '+7'),
            array('iso' => 'KE','name' => 'KENYA', 'country_code' => '+254'),
            array('iso' => 'KI','name' => 'KIRIBATI', 'country_code' => '+686'),
            array('iso' => 'KP','name' => 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF', 'country_code' => '+850'),
            array('iso' => 'KR','name' => 'KOREA, REPUBLIC OF', 'country_code' => '+82'),
            array('iso' => 'KW','name' => 'KUWAIT', 'country_code' => '+965'),
            array('iso' => 'KG','name' => 'KYRGYZSTAN', 'country_code' => '+996'),
            array('iso' => 'LA','name' => 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC', 'country_code' => '+856'),
            array('iso' => 'LV','name' => 'LATVIA', 'country_code' => '+371'),
            array('iso' => 'LB','name' => 'LEBANON', 'country_code' => '+961'),
            array('iso' => 'LS','name' => 'LESOTHO', 'country_code' => '+266'),
            array('iso' => 'LR','name' => 'LIBERIA', 'country_code' => '+231'),
            array('iso' => 'LY','name' => 'LIBYAN ARAB JAMAHIRIYA', 'country_code' => '+218'),
            array('iso' => 'LI','name' => 'LIECHTENSTEIN', 'country_code' => '+423'),
            array('iso' => 'LT','name' => 'LITHUANIA', 'country_code' => '+370'),
            array('iso' => 'LU','name' => 'LUXEMBOURG', 'country_code' => '+352'),
            array('iso' => 'MO','name' => 'MACAO', 'country_code' => '+853'),
            array('iso' => 'MK','name' => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'country_code' => '+389'),
            array('iso' => 'MG','name' => 'MADAGASCAR', 'country_code' => '+261'),
            array('iso' => 'MW','name' => 'MALAWI', 'country_code' => '+265'),
            array('iso' => 'MY','name' => 'MALAYSIA', 'country_code' => '+60'),
            array('iso' => 'MV','name' => 'MALDIVES', 'country_code' => '+960'),
            array('iso' => 'ML','name' => 'MALI', 'country_code' => '+223'),
            array('iso' => 'MT','name' => 'MALTA', 'country_code' => '+356'),
            array('iso' => 'MH','name' => 'MARSHALL ISLANDS', 'country_code' => '+692'),
            array('iso' => 'MQ','name' => 'MARTINIQUE', 'country_code' => '+596'),
            array('iso' => 'MR','name' => 'MAURITANIA', 'country_code' => '+222'),
            array('iso' => 'MU','name' => 'MAURITIUS', 'country_code' => '+230'),
            array('iso' => 'YT','name' => 'MAYOTTE', 'country_code' => '+269'),
            array('iso' => 'MX','name' => 'MEXICO', 'country_code' => '+52'),
            array('iso' => 'FM','name' => 'MICRONESIA, FEDERATED STATES OF', 'country_code' => '+691'),
            array('iso' => 'MD','name' => 'MOLDOVA, REPUBLIC OF', 'country_code' => '+373'),
            array('iso' => 'MC','name' => 'MONACO', 'country_code' => '+377'),
            array('iso' => 'MN','name' => 'MONGOLIA', 'country_code' => '+976'),
            array('iso' => 'MS','name' => 'MONTSERRAT', 'country_code' => '+1664'),
            array('iso' => 'MA','name' => 'MOROCCO', 'country_code' => '+212'),
            array('iso' => 'MZ','name' => 'MOZAMBIQUE', 'country_code' => '+258'),
            array('iso' => 'MM','name' => 'MYANMAR', 'country_code' => '+95'),
            array('iso' => 'NA','name' => 'NAMIBIA', 'country_code' => '+264'),
            array('iso' => 'NR','name' => 'NAURU', 'country_code' => '+674'),
            array('iso' => 'NP','name' => 'NEPAL', 'country_code' => '+977'),
            array('iso' => 'NL','name' => 'NETHERLANDS', 'country_code' => '+31'),
            array('iso' => 'AN','name' => 'NETHERLANDS ANTILLES', 'country_code' => '+599'),
            array('iso' => 'NC','name' => 'NEW CALEDONIA', 'country_code' => '+687'),
            array('iso' => 'NZ','name' => 'NEW ZEALAND', 'country_code' => '+64'),
            array('iso' => 'NI','name' => 'NICARAGUA', 'country_code' => '+505'),
            array('iso' => 'NE','name' => 'NIGER', 'country_code' => '+227'),
            array('iso' => 'NG','name' => 'NIGERIA', 'country_code' => '+234'),
            array('iso' => 'NU','name' => 'NIUE', 'country_code' => '+683'),
            array('iso' => 'NF','name' => 'NORFOLK ISLAND', 'country_code' => '+672'),
            array('iso' => 'MP','name' => 'NORTHERN MARIANA ISLANDS', 'country_code' => '+1670'),
            array('iso' => 'NO','name' => 'NORWAY', 'country_code' => '+47'),
            array('iso' => 'OM','name' => 'OMAN', 'country_code' => '+968'),
            array('iso' => 'PK','name' => 'PAKISTAN', 'country_code' => '+92'),
            array('iso' => 'PW','name' => 'PALAU', 'country_code' => '+680'),
            array('iso' => 'PS','name' => 'PALESTINIAN TERRITORY, OCCUPIED', 'country_code' => '+970'),
            array('iso' => 'PA','name' => 'PANAMA', 'country_code' => '+507'),
            array('iso' => 'PG','name' => 'PAPUA NEW GUINEA', 'country_code' => '+675'),
            array('iso' => 'PY','name' => 'PARAGUAY', 'country_code' => '+595'),
            array('iso' => 'PE','name' => 'PERU', 'country_code' => '+51'),
            array('iso' => 'PH','name' => 'PHILIPPINES', 'country_code' => '+63'),
            array('iso' => 'PN','name' => 'PITCAIRN', 'country_code' => '+0'),
            array('iso' => 'PL','name' => 'POLAND', 'country_code' => '+48'),
            array('iso' => 'PT','name' => 'PORTUGAL', 'country_code' => '+351'),
            array('iso' => 'PR','name' => 'PUERTO RICO', 'country_code' => '+1787'),
            array('iso' => 'QA','name' => 'QATAR', 'country_code' => '+974'),
            array('iso' => 'RE','name' => 'REUNION', 'country_code' => '+262'),
            array('iso' => 'RO','name' => 'ROMANIA', 'country_code' => '+40'),
            array('iso' => 'RU','name' => 'RUSSIAN FEDERATION', 'country_code' => '+70'),
            array('iso' => 'RW','name' => 'RWANDA', 'country_code' => '+250'),
            array('iso' => 'SH','name' => 'SAINT HELENA', 'country_code' => '+290'),
            array('iso' => 'KN','name' => 'SAINT KITTS AND NEVIS', 'country_code' => '+1869'),
            array('iso' => 'LC','name' => 'SAINT LUCIA', 'country_code' => '+1758'),
            array('iso' => 'PM','name' => 'SAINT PIERRE AND MIQUELON', 'country_code' => '+508'),
            array('iso' => 'VC','name' => 'SAINT VINCENT AND THE GRENADINES', 'country_code' => '+1784'),
            array('iso' => 'WS','name' => 'SAMOA', 'country_code' => '+684'),
            array('iso' => 'SM','name' => 'SAN MARINO', 'country_code' => '+378'),
            array('iso' => 'ST','name' => 'SAO TOME AND PRINCIPE', 'country_code' => '+239'),
            array('iso' => 'SA','name' => 'SAUDI ARABIA', 'country_code' => '+966'),
            array('iso' => 'SN','name' => 'SENEGAL', 'country_code' => '+221'),
            array('iso' => 'CS','name' => 'SERBIA AND MONTENEGRO', 'country_code' => '+381'),
            array('iso' => 'SC','name' => 'SEYCHELLES', 'country_code' => '+248'),
            array('iso' => 'SL','name' => 'SIERRA LEONE', 'country_code' => '+232'),
            array('iso' => 'SG','name' => 'SINGAPORE', 'country_code' => '+65'),
            array('iso' => 'SK','name' => 'SLOVAKIA', 'country_code' => '+421'),
            array('iso' => 'SI','name' => 'SLOVENIA', 'country_code' => '+386'),
            array('iso' => 'SB','name' => 'SOLOMON ISLANDS', 'country_code' => '+677'),
            array('iso' => 'SO','name' => 'SOMALIA', 'country_code' => '+252'),
            array('iso' => 'ZA','name' => 'SOUTH AFRICA', 'country_code' => '+27'),
            array('iso' => 'GS','name' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'country_code' => '+0'),
            array('iso' => 'ES','name' => 'SPAIN', 'country_code' => '+34'),
            array('iso' => 'LK','name' => 'SRI LANKA', 'country_code' => '+94'),
            array('iso' => 'SD','name' => 'SUDAN', 'country_code' => '+249'),
            array('iso' => 'SR','name' => 'SURINAME', 'country_code' => '+597'),
            array('iso' => 'SJ','name' => 'SVALBARD AND JAN MAYEN', 'country_code' => '+47'),
            array('iso' => 'SZ','name' => 'SWAZILAND', 'country_code' => '+268'),
            array('iso' => 'SE','name' => 'SWEDEN', 'country_code' => '+46'),
            array('iso' => 'CH','name' => 'SWITZERLAND', 'country_code' => '+41'),
            array('iso' => 'SY','name' => 'SYRIAN ARAB REPUBLIC', 'country_code' => '+963'),
            array('iso' => 'TW','name' => 'TAIWAN, PROVINCE OF CHINA', 'country_code' => '+886'),
            array('iso' => 'TJ','name' => 'TAJIKISTAN', 'country_code' => '+992'),
            array('iso' => 'TZ','name' => 'TANZANIA, UNITED REPUBLIC OF', 'country_code' => '+255'),
            array('iso' => 'TH','name' => 'THAILAND', 'country_code' => '+66'),
            array('iso' => 'TL','name' => 'TIMOR-LESTE', 'country_code' => '+670'),
            array('iso' => 'TG','name' => 'TOGO', 'country_code' => '+228'),
            array('iso' => 'TK','name' => 'TOKELAU', 'country_code' => '+690'),
            array('iso' => 'TO','name' => 'TONGA', 'country_code' => '+676'),
            array('iso' => 'TT','name' => 'TRINIDAD AND TOBAGO', 'country_code' => '+1868'),
            array('iso' => 'TN','name' => 'TUNISIA', 'country_code' => '+216'),
            array('iso' => 'TR','name' => 'TURKEY', 'country_code' => '+90'),
            array('iso' => 'TM','name' => 'TURKMENISTAN', 'country_code' => '+7370'),
            array('iso' => 'TC','name' => 'TURKS AND CAICOS ISLANDS', 'country_code' => '+1649'),
            array('iso' => 'TV','name' => 'TUVALU', 'country_code' => '+688'),
            array('iso' => 'UG','name' => 'UGANDA', 'country_code' => '+256'),
            array('iso' => 'UA','name' => 'UKRAINE', 'country_code' => '+380'),
            array('iso' => 'AE','name' => 'UNITED ARAB EMIRATES', 'country_code' => '+971'),
            array('iso' => 'GB','name' => 'UNITED KINGDOM', 'country_code' => '+44'),
            array('iso' => 'US','name' => 'UNITED STATES', 'country_code' => '+1'),
            array('iso' => 'UM','name' => 'UNITED STATES MINOR OUTLYING ISLANDS', 'country_code' => '+1'),
            array('iso' => 'UY','name' => 'URUGUAY', 'country_code' => '+598'),
            array('iso' => 'UZ','name' => 'UZBEKISTAN', 'country_code' => '+998'),
            array('iso' => 'VU','name' => 'VANUATU', 'country_code' => '+678'),
            array('iso' => 'VE','name' => 'VENEZUELA', 'country_code' => '+58'),
            array('iso' => 'VN','name' => 'VIET NAM', 'country_code' => '+84'),
            array('iso' => 'VG','name' => 'VIRGIN ISLANDS, BRITISH', 'country_code' => '+1284'),
            array('iso' => 'VI','name' => 'VIRGIN ISLANDS, U.S.', 'country_code' => '+1340'),
            array('iso' => 'WF','name' => 'WALLIS AND FUTUNA', 'country_code' => '+681'),
            array('iso' => 'EH','name' => 'WESTERN SAHARA', 'country_code' => '+212'),
            array('iso' => 'YE','name' => 'YEMEN', 'country_code' => '+967'),
            array('iso' => 'ZM','name' => 'ZAMBIA', 'country_code' => '+260'),
            array('iso' => 'ZW','name' => 'ZIMBABWE', 'country_code' => '+263'),
            array('iso' => 'RS','name' => 'SERBIA', 'country_code' => '+381'),
            array('iso' => 'AP','name' => 'ASIA PACIFIC REGION', 'country_code' => '+0'),
            array('iso' => 'ME','name' => 'MONTENEGRO', 'country_code' => '+382'),
            array('iso' => 'AX','name' => 'ALAND ISLANDS', 'country_code' => '+358'),
            array('iso' => 'BQ','name' => 'BONAIRE, SINT EUSTATIUS AND SABA', 'country_code' => '+599'),
            array('iso' => 'CW','name' => 'CURACAO', 'country_code' => '+599'),
            array('iso' => 'GG','name' => 'GUERNSEY', 'country_code' => '+44'),
            array('iso' => 'IM','name' => 'ISLE OF MAN', 'country_code' => '+44'),
            array('iso' => 'JE','name' => 'JERSEY', 'country_code' => '+44'),
            array('iso' => 'XK','name' => 'KOSOVO', 'country_code' => '+381'),
            array('iso' => 'BL','name' => 'SAINT BARTHELEMY', 'country_code' => '+590'),
            array('iso' => 'MF','name' => 'SAINT MARTIN', 'country_code' => '+590'),
            array('iso' => 'SX','name' => 'SINT MAARTEN', 'country_code' => '+1'),
            array('iso' => 'SS','name' => 'SOUTH SUDAN', 'country_code' => '+211')
          );

          DB::table('countries')->insert($countries);

    }
}